import fs from 'fs';

const data = JSON.parse(fs.readFileSync('n8n_workflows.json', 'utf8'));
const wf = data.find(w => w.id === 'YzO4pksRLgheWGUL');
const calc = wf.nodes.find(n => n.name === 'Calculate Risk Score');

const newJsCode = [
  '// Extract data from merged inputs',
  'const inputs = $input.all();',
  '',
  'const clauseData = inputs[0]?.json?.output?.clauses || [];',
  'const riskData = inputs[1]?.json?.output?.risks || [];',
  'const obligationData = inputs[2]?.json?.output?.obligations || [];',
  'const summaryData = inputs[3]?.json?.output || {};',
  '',
  '// Risk weights by clause categories',
  'const riskWeights = {',
  "  'Service Level and Support (Clause 3)': 0.16,",
  "  'Fees and Payment (Clause 4)': 0.08,",
  "  'Data Protection and Security (Clause 5)': 0.18,",
  "  'Confidentiality (Clause 6)': 0.05,",
  "  'Intellectual Property (Clause 7)': 0.08,",
  "  'Indemnification (Clause 8)': 0.10,",
  "  'Limitation of Liability (Clause 9)': 0.22,",
  "  'Term, Renewal and Termination (Clause 10)': 0.10,",
  "  'Effect of Termination (Clause 11)': 0.02,",
  "  'General / Governing Law (Clause 12)': 0.01,",
  "  'Definitions and Interpretation (Clause 1)': 0.00,",
  "  'Services and Obligations (Clause 2)': 0.00",
  '};',
  '',
  '// Risk level scores',
  'const riskScores = {',
  '  critical: 1.0,',
  '  high: 0.75,',
  '  medium: 0.5,',
  '  low: 0.25,',
  '  none: 0.0',
  '};',
  '',
  'function normalizeRiskType(type) {',
  "  const value = String(type || '').toLowerCase();",
  "  if (value.includes('liability')) return 'Limitation of Liability (Clause 9)';",
  "  if (value.includes('data protection') || value.includes('security')) return 'Data Protection and Security (Clause 5)';",
  "  if (value.includes('service level') || value.includes('sla') || value.includes('support')) return 'Service Level and Support (Clause 3)';",
  "  if (value.includes('indemn')) return 'Indemnification (Clause 8)';",
  "  if (value.includes('payment') || value.includes('fee') || value.includes('compensation')) return 'Fees and Payment (Clause 4)';",
  "  if (value.includes('effect of termination') || value.includes('data return')) return 'Effect of Termination (Clause 11)';",
  "  if (value.includes('termination') || value.includes('term') || value.includes('renewal')) return 'Term, Renewal and Termination (Clause 10)';",
  "  if (value.includes('ip') || value.includes('intellectual property')) return 'Intellectual Property (Clause 7)';",
  "  if (value.includes('confidential')) return 'Confidentiality (Clause 6)';",
  "  if (value.includes('governing law') || value.includes('dispute') || value.includes('general')) return 'General / Governing Law (Clause 12)';",
  "  if (value.includes('service') || value.includes('modification') || value.includes('guarantee') || value.includes('duties') || value.includes('work scope')) return 'Services and Obligations (Clause 2)';",
  '  return null;',
  '}',
  '',
  '// Calculate weighted risk score',
  'let scoreBreakdown = {};',
  'let totalWeightedScore = 0;',
  '',
  'let redFlags = [];',
  'let recommendations = [];',
  '',
  'riskData.forEach(risk => {',
  '  const matchedKey = riskWeights[risk.clause_type] !== undefined',
  '    ? risk.clause_type',
  '    : normalizeRiskType(risk.clause_type);',
  '  const weight = matchedKey ? (riskWeights[matchedKey] ?? 0) : 0;',
  '  const score = riskScores[risk.risk_level?.toLowerCase()] ?? 0;',
  '',
  '  const weightedScore = score * weight;',
  '',
  "  scoreBreakdown[(matchedKey || risk.clause_type) + '_risk'] = score;",
  '',
  '  totalWeightedScore += weightedScore;',
  '',
  '  // High and critical risks become red flags',
  '  if (',
  "    risk.risk_level?.toLowerCase() === 'critical' ||",
  "    risk.risk_level?.toLowerCase() === 'high'",
  '  ) {',
  '    redFlags.push(risk.risk_description);',
  '    recommendations.push(risk.recommendation);',
  '  }',
  '});',
  '',
  '// Check for missing critical clauses',
  'const criticalClauses = [',
  "  'payment_terms',",
  "  'liability',",
  "  'termination'",
  '];',
  '',
  'const foundClauses = clauseData.map(c => c.clause_type);',
  '',
  'criticalClauses.forEach(critical => {',
  '  if (!foundClauses.includes(critical)) {',
  '    redFlags.push("Missing critical clause: " + critical);',
  '    recommendations.push("Add " + critical + " clause to contract");',
  '  }',
  '});',
  '',
  '// Check AI confidence levels',
  'const lowConfidenceItems = [',
  '  ...clauseData,',
  '  ...riskData',
  '].filter(item => {',
  "  return typeof item.ai_confidence === 'number' &&",
  '         item.ai_confidence < 0.6;',
  '});',
  '',
  'if (lowConfidenceItems.length > 0) {',
  '  redFlags.push(',
  '    lowConfidenceItems.length + " items flagged for manual legal review (low AI confidence)"',
  '  );',
  '',
  '  recommendations.push(',
  "    'Schedule legal review for low-confidence extractions'",
  '  );',
  '}',
  '',
  '// Final risk score',
  'const overallRiskScore = Math.min(',
  '  1.0,',
  '  Math.round(totalWeightedScore * 100) / 100',
  ');',
  '',
  'return {',
  '  clauses: clauseData,',
  '  risks: riskData,',
  '  obligations: obligationData,',
  '  summary: summaryData,',
  '',
  '  overall_risk_score: overallRiskScore,',
  '',
  '  score_breakdown: scoreBreakdown,',
  '',
  '  red_flags: redFlags,',
  '',
  '  recommendations: recommendations,',
  '',
  '  calculated_at: new Date().toISOString(),',
  '  contractId: inputs[0]?.json?.contractId || inputs[1]?.json?.contractId || inputs[2]?.json?.contractId || inputs[3]?.json?.contractId || null',
  '};'
].join('\n');

calc.parameters.jsCode = newJsCode;
fs.writeFileSync('updated_wf_clean.json', JSON.stringify(wf, null, 2), 'utf8');
console.log('SUCCESS: Written updated_wf_clean.json');
