import React, { useEffect, useState } from 'react';
import { useParams, useNavigate, Link } from 'react-router-dom';
import { Loader2 } from 'lucide-react';
import { RiskBadge } from '../components/RiskBadge';
import { Tabs, TabItem } from '../components/Tabs';
import { api, ContractDetail } from '../services/api';
import { RiskLevel } from '../data/mockData';

type Tab = 'overview' | 'risks' | 'obligations';

export const ContractDetails: React.FC = () => {
  const { id } = useParams<{ id: string }>();
  const navigate = useNavigate();
  const [activeTab, setActiveTab] = useState<Tab>('risks');
  const [contract, setContract]   = useState<ContractDetail | null>(null);
  const [loading, setLoading]     = useState<boolean>(true);
  const [error, setError]         = useState<string | null>(null);

  useEffect(() => {
    if (!id) return;
    let isMounted = true;
    setLoading(true);
    api
      .getContractById(id)
      .then((data) => { if (isMounted) { setContract(data); setLoading(false); } })
      .catch(() => { if (isMounted) { setError('Failed to load contract.'); setLoading(false); } });
    return () => { isMounted = false; };
  }, [id]);

  /* Obligations tab navigates to its own route — same as original */
  const handleTabChange = (tab: string) => {
    if (tab === 'obligations') {
      navigate(`/contracts/${id}/obligations`);
    } else {
      setActiveTab(tab as Tab);
    }
  };

  const normalizeRiskLevel = (lvl?: string): RiskLevel => {
    const u = (lvl ?? '').toUpperCase();
    if (u === 'CRITICAL') return 'CRITICAL';
    if (u === 'HIGH')     return 'HIGH';
    if (u === 'MEDIUM')   return 'MEDIUM';
    return 'LOW';
  };

  const formatDate = (dateStr?: string) => {
    if (!dateStr) return 'N/A';
    try {
      return new Date(dateStr)
        .toLocaleDateString('en-GB', {
          day: '2-digit',
          month: 'short',
          year: 'numeric',
        })
        .toUpperCase();
    } catch {
      return dateStr.toUpperCase();
    }
  };

  /* ── Loading ──────────────────────────────────────── */
  if (loading) {
    return (
      <div className="max-w-7xl mx-auto px-6 lg:px-12 py-20 flex items-center gap-3 text-neutral-400">
        <Loader2 className="w-4 h-4 animate-spin" />
        <span className="text-[11px] tracking-[0.2em] uppercase animate-pulse">
          LOADING CONTRACT...
        </span>
      </div>
    );
  }

  /* ── Error ────────────────────────────────────────── */
  if (error || !contract) {
    return (
      <div className="max-w-7xl mx-auto px-6 lg:px-12 py-16 space-y-8">
        <Link
          to="/dashboard"
          className="inline-flex items-center gap-1.5 text-[11px] tracking-[0.14em] uppercase text-neutral-500 hover:text-black transition-colors"
        >
          ← DASHBOARD
        </Link>
        <div className="border border-black p-8">
          <p className="text-[10px] tracking-[0.2em] uppercase text-neutral-500 mb-2">ERROR</p>
          <p className="text-base font-medium text-black">{error ?? 'Failed to load contract.'}</p>
        </div>
      </div>
    );
  }

  /* ── Derived values ─────────────────────────────── */
  const risks      = contract.risks ?? [];
  const riskLevel  = normalizeRiskLevel(contract.riskLevel);
  const overviewSummary =
    contract.summary?.overall_assessment ??
    contract.summary?.major_obligations ??
    contract.summary?.key_terms ??
    'Contract analysis overview generated by AI.';

  const partyLine =
    contract.client && contract.vendor
      ? `${contract.client} × ${contract.vendor}`
      : contract.client ?? contract.vendor ?? '';

  const tabItems: TabItem[] = [
    { id: 'overview',     label: 'OVERVIEW'                },
    { id: 'risks',        label: 'RISKS', count: risks.length },
    { id: 'obligations',  label: 'OBLIGATIONS'             },
  ];

  /* ── Render ─────────────────────────────────────── */
  return (
    <div className="max-w-7xl mx-auto px-6 lg:px-12 py-12 md:py-16">

      {/* Back */}
      <Link
        to="/dashboard"
        className="inline-flex items-center gap-1.5 text-[11px] tracking-[0.14em] uppercase text-neutral-500 hover:text-black transition-colors mb-8"
      >
        ← DASHBOARD
      </Link>

      {/* ── Contract Header ────────────────────────── */}
      {partyLine && (
        <p className="text-[10px] tracking-[0.26em] uppercase text-neutral-400 mb-3 font-medium">
          {partyLine}
        </p>
      )}
      <h1 className="text-3xl sm:text-4xl md:text-5xl lg:text-6xl font-medium tracking-tight leading-[1.05] uppercase text-black mb-3 max-w-5xl">
        {contract.name.replace(/_/g, ' ')}
      </h1>
      {contract.contractType && (
        <p className="text-xs font-mono uppercase tracking-[0.18em] text-neutral-400 mb-8">
          {contract.contractType}
        </p>
      )}

      <hr className="border-black mb-10" />

      {/* ── Risk Score Visual Anchor + Metadata Strip ──────────────────── */}
      <div className="grid grid-cols-1 lg:grid-cols-12 gap-10 lg:gap-16 mb-12 items-end">

        {/* Risk score visual anchor (large typography, pure whitespace) */}
        <div className="lg:col-span-5 space-y-3">
          <p className="text-[10px] tracking-[0.24em] uppercase text-neutral-400 font-medium">
            COMPUTED RISK SCORE
          </p>
          <div className="flex items-baseline gap-4">
            <span className="text-8xl sm:text-9xl font-medium tabular-nums font-mono leading-none tracking-tight text-black">
              {contract.riskScore}%
            </span>
            <RiskBadge level={riskLevel} className="text-xs px-3 py-1 font-semibold" />
          </div>
        </div>

        {/* Metadata grid (clean rules & whitespace, no boxy cards) */}
        <div className="lg:col-span-7 grid grid-cols-2 sm:grid-cols-4 gap-6 pt-6 lg:pt-0 border-t lg:border-t-0 lg:border-l border-neutral-200 lg:pl-10">
          {[
            { label: 'CLIENT',    value: contract.client          ?? 'N/A' },
            { label: 'VENDOR',    value: contract.vendor          ?? 'N/A' },
            { label: 'EFFECTIVE', value: formatDate(contract.effectiveDate) },
            { label: 'EXPIRES',   value: formatDate(contract.expirationDate) },
          ].map(({ label, value }) => (
            <div key={label} className="space-y-1">
              <p className="text-[10px] tracking-[0.22em] uppercase text-neutral-400 font-medium">
                {label}
              </p>
              <p className="text-sm font-medium text-black leading-snug break-words">
                {value}
              </p>
            </div>
          ))}
        </div>
      </div>

      <hr className="border-neutral-200 mb-8" />

      {/* ── Tabs ──────────────────────────────────── */}
      <div className="mb-10">
        <Tabs
          tabs={tabItems}
          active={activeTab}
          onChange={handleTabChange}
        />
      </div>

      {/* ── Overview Tab ──────────────────────────── */}
      {activeTab === 'overview' && (
        <div className="max-w-4xl space-y-10">
          <div>
            <h2 className="text-[11px] tracking-[0.24em] uppercase text-neutral-400 font-medium mb-4">
              EXECUTIVE OVERVIEW
            </h2>
            <p className="text-lg md:text-xl text-black font-normal leading-relaxed">
              {overviewSummary}
            </p>
          </div>

          <hr className="border-neutral-200" />

          <div className="grid grid-cols-1 sm:grid-cols-3 gap-8">
            <div>
              <p className="text-[10px] tracking-[0.22em] uppercase text-neutral-400 mb-1 font-medium">
                AGREEMENT TYPE
              </p>
              <p className="text-sm md:text-base font-medium text-black">
                {contract.contractType ?? contract.summary?.contract_type ?? 'Contract'}
              </p>
            </div>
            <div>
              <p className="text-[10px] tracking-[0.22em] uppercase text-neutral-400 mb-1 font-medium">
                SOURCE DOCUMENT
              </p>
              <p className="text-sm md:text-base font-medium text-black font-mono truncate">
                {contract.originalFileName ?? 'Uploaded Document'}
              </p>
            </div>
            <div>
              <p className="text-[10px] tracking-[0.22em] uppercase text-neutral-400 mb-1 font-medium">
                STATED VALUE
              </p>
              <p className="text-sm md:text-base font-medium text-black">
                {contract.value ?? contract.summary?.value ?? 'N/A'}
              </p>
            </div>
          </div>
        </div>
      )}

      {/* ── Risks Tab (Editorial Report Style) ─────────────────────── */}
      {activeTab === 'risks' && (
        <div>
          <div className="flex items-baseline justify-between mb-8 pb-3 border-b border-black">
            <h2 className="text-[11px] tracking-[0.24em] uppercase text-neutral-500 font-medium">
              RISK FINDINGS
            </h2>
            <span className="text-[10px] tracking-[0.16em] uppercase text-neutral-400 font-mono">
              {risks.length} FINDING{risks.length !== 1 ? 'S' : ''}
            </span>
          </div>

          {risks.length === 0 ? (
            <div className="py-24 border border-dashed border-neutral-200 text-center">
              <p className="text-[11px] tracking-[0.22em] uppercase text-neutral-400">
                NO SIGNIFICANT RISKS IDENTIFIED.
              </p>
            </div>
          ) : (
            <div className="divide-y divide-neutral-200">
              {risks.map((finding, idx) => {
                const level = normalizeRiskLevel(finding.risk_level);
                return (
                  <div key={idx} className="py-10 first:pt-4">
                    <div className="grid grid-cols-12 gap-6 md:gap-10">
                      {/* Left Column: Big index + Monochrome Risk Level */}
                      <div className="col-span-12 md:col-span-3 space-y-3">
                        <span className="text-4xl md:text-5xl font-mono font-medium tracking-tight text-neutral-300 block leading-none">
                          {String(idx + 1).padStart(2, '0')}
                        </span>
                        <RiskBadge level={level} className="text-xs px-3 py-1 font-semibold" />
                      </div>

                      {/* Right Column: Title, Description, and Editorial Recommendation */}
                      <div className="col-span-12 md:col-span-9 space-y-5">
                        <h3 className="text-lg md:text-xl font-medium uppercase tracking-tight text-black leading-snug">
                          {finding.clause_type
                            ? finding.clause_type.replace(/_/g, ' ')
                            : `Risk Finding #${idx + 1}`}
                        </h3>

                        {finding.risk_description && (
                          <p className="text-base text-neutral-800 leading-relaxed font-normal">
                            {finding.risk_description}
                          </p>
                        )}

                        {finding.recommendation && (
                          <div className="border-l-2 border-black pl-5 pt-1 pb-1 mt-4">
                            <p className="text-[10px] tracking-[0.22em] uppercase text-neutral-500 mb-1.5 font-medium">
                              RECOMMENDATION
                            </p>
                            <p className="text-sm md:text-base text-black leading-relaxed">
                              {finding.recommendation}
                            </p>
                          </div>
                        )}
                      </div>
                    </div>
                  </div>
                );
              })}
            </div>
          )}
        </div>
      )}
    </div>
  );
};
