import React, { useEffect, useState } from 'react';
import { useParams, useNavigate, Link } from 'react-router-dom';
import { Loader2 } from 'lucide-react';
import { RiskBadge } from '../components/RiskBadge';
import { Tabs, TabItem } from '../components/Tabs';
import { api, ContractDetail } from '../services/api';
import { RiskLevel } from '../data/mockData';

type Tab = 'overview' | 'risks' | 'obligations';

export const ContractDetails: React.FC = () => {
  const { id } = useParams<{ id: string }>();
  const navigate = useNavigate();
  const [activeTab, setActiveTab] = useState<Tab>('risks');
  const [contract, setContract]   = useState<ContractDetail | null>(null);
  const [loading, setLoading]     = useState<boolean>(true);
  const [error, setError]         = useState<string | null>(null);

  useEffect(() => {
    if (!id) return;
    let isMounted = true;
    setLoading(true);
    api
      .getContractById(id)
      .then((data) => { if (isMounted) { setContract(data); setLoading(false); } })
      .catch(() => { if (isMounted) { setError('Failed to load contract.'); setLoading(false); } });
    return () => { isMounted = false; };
  }, [id]);

  /* Obligations tab navigates to its own route — same as original */
  const handleTabChange = (tab: string) => {
    if (tab === 'obligations') {
      navigate(`/contracts/${id}/obligations`);
    } else {
      setActiveTab(tab as Tab);
    }
  };

  const normalizeRiskLevel = (lvl?: string): RiskLevel => {
    const u = (lvl ?? '').toUpperCase();
    if (u === 'CRITICAL') return 'CRITICAL';
    if (u === 'HIGH')     return 'HIGH';
    if (u === 'MEDIUM')   return 'MEDIUM';
    return 'LOW';
  };

  const formatDate = (dateStr?: string) => {
    if (!dateStr) return 'N/A';
    try {
      return new Date(dateStr).toLocaleDateString('en-GB', {
        day: '2-digit', month: 'short', year: 'numeric',
      });
    } catch { return dateStr; }
  };

  /* ── Loading ──────────────────────────────────────── */
  if (loading) {
    return (
      <div className="max-w-7xl mx-auto px-6 lg:px-12 py-20 flex items-center gap-3 text-neutral-400">
        <Loader2 className="w-4 h-4 animate-spin" />
        <span className="text-[11px] tracking-[0.2em] uppercase animate-pulse">
          LOADING CONTRACT...
        </span>
      </div>
    );
  }

  /* ── Error ────────────────────────────────────────── */
  if (error || !contract) {
    return (
      <div className="max-w-7xl mx-auto px-6 lg:px-12 py-16 space-y-8">
        <Link
          to="/dashboard"
          className="inline-flex items-center gap-1.5 text-[11px] tracking-[0.14em] uppercase text-neutral-500 hover:text-black transition-colors"
        >
          ← DASHBOARD
        </Link>
        <div className="border border-black p-8">
          <p className="text-[10px] tracking-[0.2em] uppercase text-neutral-500 mb-2">ERROR</p>
          <p className="text-base font-medium text-black">{error ?? 'Failed to load contract.'}</p>
        </div>
      </div>
    );
  }

  /* ── Derived values ─────────────────────────────── */
  const risks      = contract.risks ?? [];
  const riskLevel  = normalizeRiskLevel(contract.riskLevel);
  const overviewSummary =
    contract.summary?.overall_assessment ??
    contract.summary?.major_obligations ??
    contract.summary?.key_terms ??
    'Contract analysis overview generated by AI.';

  const partyLine =
    contract.client && contract.vendor
      ? `${contract.client} × ${contract.vendor}`
      : contract.client ?? contract.vendor ?? '';

  const tabItems: TabItem[] = [
    { id: 'overview',     label: 'OVERVIEW'                },
    { id: 'risks',        label: 'RISKS', count: risks.length },
    { id: 'obligations',  label: 'OBLIGATIONS'             },
  ];

  /* ── Render ─────────────────────────────────────── */
  return (
    <div className="max-w-7xl mx-auto px-6 lg:px-12 py-12 md:py-16">

      {/* Back */}
      <Link
        to="/dashboard"
        className="inline-flex items-center gap-1.5 text-[11px] tracking-[0.14em] uppercase text-neutral-500 hover:text-black transition-colors mb-8"
      >
        ← DASHBOARD
      </Link>

      {/* ── Contract Header ────────────────────────── */}
      {partyLine && (
        <p className="text-[11px] tracking-[0.22em] uppercase text-neutral-500 mb-2">
          {partyLine}
        </p>
      )}
      <h1 className="text-3xl md:text-4xl lg:text-5xl font-medium tracking-tight leading-tight text-black mb-2">
        {contract.name.toUpperCase()}
      </h1>
      {contract.contractType && (
        <p className="text-sm text-neutral-500 mb-8">{contract.contractType}</p>
      )}

      <hr className="border-black mb-8" />

      {/* ── Risk Score + Metadata ──────────────────── */}
      <div className="grid grid-cols-1 md:grid-cols-2 gap-8 mb-10">

        {/* Risk score block */}
        <div className="flex items-end gap-5">
          <div>
            <p className="text-[10px] tracking-[0.22em] uppercase text-neutral-500 mb-2">
              RISK SCORE
            </p>
            <p className="text-7xl md:text-8xl font-medium tabular-nums leading-none text-black">
              {contract.riskScore}%
            </p>
          </div>
          <div className="mb-2">
            <RiskBadge level={riskLevel} className="text-xs px-3 py-1" />
          </div>
        </div>

        {/* Metadata grid */}
        <div className="grid grid-cols-2 gap-x-8 gap-y-5">
          {[
            { label: 'CLIENT',    value: contract.client          ?? 'N/A' },
            { label: 'VENDOR',    value: contract.vendor          ?? 'N/A' },
            { label: 'EFFECTIVE', value: formatDate(contract.effectiveDate) },
            { label: 'EXPIRES',   value: formatDate(contract.expirationDate) },
          ].map(({ label, value }) => (
            <div key={label}>
              <p className="text-[10px] tracking-[0.22em] uppercase text-neutral-400 mb-0.5">
                {label}
              </p>
              <p className="text-sm font-medium text-black leading-snug">{value}</p>
            </div>
          ))}
        </div>
      </div>

      <hr className="border-neutral-200 mb-8" />

      {/* ── Tabs ──────────────────────────────────── */}
      <div className="mb-8">
        <Tabs
          tabs={tabItems}
          active={activeTab}
          onChange={handleTabChange}
        />
      </div>

      {/* ── Overview Tab ──────────────────────────── */}
      {activeTab === 'overview' && (
        <div className="max-w-3xl space-y-8">
          <div>
            <h2 className="text-[11px] tracking-[0.22em] uppercase text-neutral-500 mb-5">
              OVERVIEW
            </h2>
            <p className="text-base text-black leading-relaxed">{overviewSummary}</p>
          </div>

          <hr className="border-neutral-200" />

          <div className="grid grid-cols-1 sm:grid-cols-3 gap-6">
            <div>
              <p className="text-[10px] tracking-[0.22em] uppercase text-neutral-400 mb-1">TYPE</p>
              <p className="text-sm font-medium text-black">
                {contract.contractType ?? contract.summary?.contract_type ?? 'Contract'}
              </p>
            </div>
            <div>
              <p className="text-[10px] tracking-[0.22em] uppercase text-neutral-400 mb-1">DOCUMENT</p>
              <p className="text-sm font-medium text-black">
                {contract.originalFileName ?? 'Uploaded Document'}
              </p>
            </div>
            <div>
              <p className="text-[10px] tracking-[0.22em] uppercase text-neutral-400 mb-1">VALUE</p>
              <p className="text-sm font-medium text-black">
                {contract.value ?? contract.summary?.value ?? 'N/A'}
              </p>
            </div>
          </div>
        </div>
      )}

      {/* ── Risks Tab ─────────────────────────────── */}
      {activeTab === 'risks' && (
        <div>
          <div className="flex items-baseline justify-between mb-8">
            <h2 className="text-[11px] tracking-[0.22em] uppercase text-neutral-500">
              RISK FINDINGS
            </h2>
            <span className="text-[10px] tracking-[0.14em] uppercase text-neutral-400">
              {risks.length} FINDING{risks.length !== 1 ? 'S' : ''}
            </span>
          </div>

          {risks.length === 0 ? (
            <div className="py-20 border border-dashed border-neutral-200 text-center">
              <p className="text-[11px] tracking-[0.22em] uppercase text-neutral-400">
                NO SIGNIFICANT RISKS IDENTIFIED.
              </p>
            </div>
          ) : (
            <div>
              {risks.map((finding, idx) => {
                const level = normalizeRiskLevel(finding.risk_level);
                return (
                  <div key={idx}>
                    <div className="py-8 grid grid-cols-12 gap-4 md:gap-8">
                      {/* Index + Badge column */}
                      <div className="col-span-12 md:col-span-3 flex items-start gap-4">
                        <span className="text-[10px] tracking-[0.18em] text-neutral-400 tabular-nums mt-0.5 shrink-0">
                          {String(idx + 1).padStart(2, '0')}
                        </span>
                        <RiskBadge level={level} />
                      </div>

                      {/* Content column */}
                      <div className="col-span-12 md:col-span-9 space-y-4">
                        <h3
                          className={`tracking-wide uppercase font-medium ${
                            level === 'CRITICAL' ? 'text-base text-black' : 'text-sm text-black'
                          }`}
                        >
                          {finding.clause_type
                            ? finding.clause_type.replace(/_/g, ' ')
                            : `Risk Finding #${idx + 1}`}
                        </h3>

                        {finding.risk_description && (
                          <p className="text-sm text-neutral-700 leading-relaxed">
                            {finding.risk_description}
                          </p>
                        )}

                        {finding.recommendation && (
                          <div className="border-l-2 border-black pl-4">
                            <p className="text-[10px] tracking-[0.18em] uppercase text-neutral-500 mb-1">
                              RECOMMENDATION
                            </p>
                            <p className="text-sm text-black leading-relaxed">
                              {finding.recommendation}
                            </p>
                          </div>
                        )}
                      </div>
                    </div>

                    {idx < risks.length - 1 && (
                      <hr className="border-neutral-100" />
                    )}
                  </div>
                );
              })}
            </div>
          )}
        </div>
      )}
    </div>
  );
};
