import React, { useEffect, useState } from 'react';
import { useParams, useNavigate } from 'react-router-dom';
import { ArrowLeft, AlertTriangle, Loader2, AlertCircle } from 'lucide-react';
import { Button } from '../components/Button';
import { RiskBadge } from '../components/RiskBadge';
import { api, ContractDetail } from '../services/api';
import { RiskLevel } from '../data/mockData';

type Tab = 'overview' | 'risks' | 'obligations';

export const ContractDetails: React.FC = () => {
  const { id } = useParams<{ id: string }>();
  const navigate = useNavigate();
  const [activeTab, setActiveTab] = useState<Tab>('risks');
  const [contract, setContract] = useState<ContractDetail | null>(null);
  const [loading, setLoading] = useState<boolean>(true);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    if (!id) return;
    let isMounted = true;
    setLoading(true);
    api
      .getContractById(id)
      .then((data) => {
        if (isMounted) {
          setContract(data);
          setLoading(false);
        }
      })
      .catch(() => {
        if (isMounted) {
          setError('Failed to load contract.');
          setLoading(false);
        }
      });

    return () => {
      isMounted = false;
    };
  }, [id]);

  const handleTabClick = (tab: Tab) => {
    if (tab === 'obligations') {
      navigate('/contracts/' + id + '/obligations');
    } else {
      setActiveTab(tab);
    }
  };

  const normalizeRiskLevel = (lvl?: string): RiskLevel => {
    const upper = (lvl || '').toUpperCase();
    if (upper === 'CRITICAL') return 'CRITICAL';
    if (upper === 'HIGH') return 'HIGH';
    if (upper === 'MEDIUM') return 'MEDIUM';
    return 'LOW';
  };

  if (loading) {
    return (
      <div className="p-12 flex items-center justify-center gap-2 text-neutral-500 text-sm">
        <Loader2 className="w-5 h-5 animate-spin" />
        <span>Loading contract...</span>
      </div>
    );
  }

  if (error || !contract) {
    return (
      <div className="space-y-4">
        <Button to="/" variant="outline" className="gap-2 text-xs py-1.5 px-3">
          <ArrowLeft className="w-3.5 h-3.5" />
          <span>Back</span>
        </Button>
        <div className="p-8 bg-white rounded-xl border border-rose-200 flex items-center gap-2 text-rose-700 text-sm">
          <AlertCircle className="w-5 h-5" />
          <span>{error || 'Failed to load contract.'}</span>
        </div>
      </div>
    );
  }

  const risks = contract.risks || [];
  const overviewSummary =
    contract.summary?.overall_assessment ||
    contract.summary?.major_obligations ||
    contract.summary?.key_terms ||
    'Contract analysis overview generated by AI.';

  return (
    <div className="space-y-6">
      <div>
        <Button to="/" variant="outline" className="gap-2 mb-4 text-xs py-1.5 px-3">
          <ArrowLeft className="w-3.5 h-3.5" />
          <span>Back</span>
        </Button>

        <div className="bg-white rounded-xl border border-neutral-200 p-6 shadow-xs space-y-6">
          <div className="flex flex-col md:flex-row md:items-start md:justify-between gap-4">
            <div>
              <h1 className="text-xl sm:text-2xl font-semibold text-neutral-900">
                {contract.name}
              </h1>
              <p className="text-xs text-neutral-500 mt-1 font-mono">Contract ID: {id}</p>
            </div>

            <div className="flex items-center gap-4 bg-neutral-50 border border-neutral-200 rounded-lg p-3 self-start">
              <div>
                <p className="text-xs text-neutral-500 font-medium uppercase">Risk Score</p>
                <p className="text-2xl font-bold text-neutral-900">{contract.riskScore}%</p>
              </div>
              <div className="h-8 w-px bg-neutral-200" />
              <div>
                <p className="text-xs text-neutral-500 font-medium uppercase mb-1">Risk Level</p>
                <RiskBadge level={normalizeRiskLevel(contract.riskLevel)} />
              </div>
            </div>
          </div>

          <div className="border-t border-neutral-200 pt-4">
            <h2 className="text-xs font-semibold text-neutral-500 uppercase tracking-wider mb-3">
              Parties
            </h2>
            <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
              <div className="p-3 bg-neutral-50 rounded-lg border border-neutral-200">
                <p className="text-xs text-neutral-500 font-medium">Client</p>
                <p className="text-sm font-semibold text-neutral-900 mt-0.5">
                  {contract.client || 'N/A'}
                </p>
              </div>
              <div className="p-3 bg-neutral-50 rounded-lg border border-neutral-200">
                <p className="text-xs text-neutral-500 font-medium">Vendor</p>
                <p className="text-sm font-semibold text-neutral-900 mt-0.5">
                  {contract.vendor || 'N/A'}
                </p>
              </div>
            </div>
          </div>
        </div>
      </div>

      <div className="flex border-b border-neutral-200 gap-2">
        <button
          onClick={() => handleTabClick('overview')}
          className={
            'px-4 py-2 text-sm font-medium border-b-2 transition-colors cursor-pointer ' +
            (activeTab === 'overview'
              ? 'border-neutral-900 text-neutral-900'
              : 'border-transparent text-neutral-500 hover:text-neutral-700')
          }
        >
          Overview
        </button>
        <button
          onClick={() => handleTabClick('risks')}
          className={
            'px-4 py-2 text-sm font-medium border-b-2 transition-colors cursor-pointer ' +
            (activeTab === 'risks'
              ? 'border-neutral-900 text-neutral-900'
              : 'border-transparent text-neutral-500 hover:text-neutral-700')
          }
        >
          Risks ({risks.length})
        </button>
        <button
          onClick={() => handleTabClick('obligations')}
          className="px-4 py-2 text-sm font-medium border-b-2 border-transparent text-neutral-500 hover:text-neutral-700 cursor-pointer"
        >
          Obligations
        </button>
      </div>

      {activeTab === 'overview' && (
        <div className="bg-white rounded-xl border border-neutral-200 p-6 space-y-4 shadow-xs">
          <h3 className="text-base font-semibold text-neutral-900">Contract Overview</h3>
          <p className="text-sm text-neutral-600 leading-relaxed">
            {overviewSummary}
          </p>
          <div className="pt-4 border-t border-neutral-200 grid grid-cols-1 sm:grid-cols-3 gap-4 text-sm">
            <div>
              <p className="text-xs text-neutral-500 font-medium">Agreement Type</p>
              <p className="font-medium text-neutral-800 mt-0.5">
                {contract.contractType || contract.summary?.contract_type || 'Contract'}
              </p>
            </div>
            <div>
              <p className="text-xs text-neutral-500 font-medium">Original File</p>
              <p className="font-medium text-neutral-800 mt-0.5">
                {contract.originalFileName || 'Uploaded Document'}
              </p>
            </div>
            <div>
              <p className="text-xs text-neutral-500 font-medium">Value</p>
              <p className="font-medium text-neutral-800 mt-0.5">
                {contract.value || contract.summary?.value || 'N/A'}
              </p>
            </div>
          </div>
        </div>
      )}

      {activeTab === 'risks' && (
        <div className="space-y-4">
          <div className="flex items-center justify-between">
            <h3 className="text-base font-semibold text-neutral-900">Identified Risks & Recommendations</h3>
            <span className="text-xs text-neutral-500">{risks.length} findings found</span>
          </div>

          {risks.length === 0 ? (
            <div className="p-8 bg-white rounded-xl border border-neutral-200 text-center text-neutral-500 text-sm">
              No significant risks identified in this contract.
            </div>
          ) : (
            <div className="space-y-3">
              {risks.map((finding, idx) => (
                <div
                  key={idx}
                  className="bg-white rounded-xl border border-neutral-200 p-5 shadow-xs space-y-3"
                >
                  <div className="flex items-center justify-between gap-2">
                    <div className="flex items-center gap-2">
                      <AlertTriangle className="w-4 h-4 text-neutral-500 shrink-0" />
                      <h4 className="text-sm font-semibold text-neutral-900">
                        {finding.clause_type ? finding.clause_type.replace(/_/g, ' ').toUpperCase() : `Risk Finding #${idx + 1}`}
                      </h4>
                    </div>
                    <RiskBadge level={normalizeRiskLevel(finding.risk_level)} />
                  </div>

                  {finding.risk_description && (
                    <p className="text-sm text-neutral-700 bg-neutral-50 p-3 rounded-lg border border-neutral-200/70 font-mono text-xs leading-relaxed">
                      "{finding.risk_description}"
                    </p>
                  )}

                  {finding.recommendation && (
                    <div className="pt-2">
                      <p className="text-xs font-semibold text-neutral-500 uppercase tracking-wide">
                        Recommendation:
                      </p>
                      <p className="text-sm text-neutral-700 mt-1 leading-relaxed">
                        {finding.recommendation}
                      </p>
                    </div>
                  )}
                </div>
              ))}
            </div>
          )}
        </div>
      )}
    </div>
  );
};
